### ISSUE TITLE
Bitcoin/Ethereum IBC via subjective data

### ISSUE THREAD

**Issue by slyon** [EOSIO/spec-repo#14]
[Contract Access To Subjective Data](https://github.com/EOSIO/spec-repo/blob/master/esr_subjective_data.md)

Would this also allow contracts to ask BPs for specific/latest BTC/ETH headers or block hashes, in order to verify Merkle proofs inside an EOS contract? Of course only if 15/21 BPs confirm the same block headers. Could this allow for real IBC with the Bitcoin/Ethereum chains...?

**Comment by arhag** [comment]
The generalization of what you are asking for is for the block producers to use the subjective data feature of the linked ESR to be used as an oracle service. While this could be possible, it unnecessarily mixes concerns. There is no reason the active block producers of the network need to be the oracle for a specific use case of a smart contract.

For example, in the case of your use case, it is possible for the contract on EOSIO to validate Bitcoin or Ethereum block headers according to their light validation consensus rules. This allows anyone (not just trusted entities) to provide the block headers to the contract. Trust is not required because the contract is able to validate the user-submitted input (the block headers). It simply works on the assumption that there is at least one honest actor out there willing to feed valid block headers into the smart contract. This is possible to do today on EOSIO blockchains without any of the additional consensus upgrades proposed in the spec repo.

**Comment by slyon** [comment]
Thanks for your explanation. If this is possible in a trustless way,it is even better!
